server:
  port: 8088

logging:
  level:
    root: WARN
    org.springframework: INFO
    org.hibernate.type.descriptor.sql: TRACE #show sql parameters
    hr.biss: TRACE

spring:

  profiles:
    active: development

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanagementdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true  # get rid of one hibernate warning
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true # show each sql executed
    properties:
      hibernate:
        #format_sql: true # format executed sql
        cache:
          use_second_level_cache: false


  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/liquibase.xml
    parameters:
      populate-initial-data: true
      postgre-partitioning: false

